apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: final
  labels:
    app: mysql
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      component: backend
  template:
    metadata:
      labels:
        app: mysql
        component: backend
    spec:
      serviceAccountName: clo835   # Assign the created ServiceAccount
      containers:
      - name: mysql-db
        image: 487784775349.dkr.ecr.us-east-1.amazonaws.com/clo835_group12:dbv1.0
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secrets
                key: mysql-root-password
          - name: MYSQL_DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: mysql-secrets
                key: mysql-database-user
          - name: DBNAME
            valueFrom:
              configMapKeyRef:
                name: configmap-g12
                key: DBNAME      
        ports:
        - containerPort: 3306
          protocol: TCP
