apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
    component: backend
spec:
  selector:
    matchLabels:
      app: mysql
      component: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
        component: backend
    spec:
      serviceAccountName:   # Assign the created ServiceAccount
      containers:
      - name: mysql-db
        image: 487784775349.dkr.ecr.us-east-1.amazonaws.com/clo835_group12:dbv1.0
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secrets
                key: mysql-root-password
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: mysql-secrets
                key: mysql-database-user
       
        ports:
        - containerPort: 3306
          protocol: TCP
