apiVersion: v1
kind: ServiceAccount
metadata: 
  name: clo835-group12
  namespace: final-project  # Specify the namespace here
  annotations: 
    eks.amazonaws.com/role-arn: arn:aws:iam::867782315616:role/LabRole

  